version: 2

builds:
  - binary: jlv
    main: ./cmd/jlv
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
    goarm:
      - "6"
    ignore:
      - goos: darwin
        goarch: "386"
    env:
      - CGO_ENABLED=0

gomod:
  proxy: false

archives:
  - name_template: "{{.Binary}}_{{.Os}}_{{.Arch}}"
    files:
      - README.md
      - LICENSE
    format_overrides:
      - goos: windows
        format: zip

release:
  draft: false

snapshot:
  name_template: "{{.Tag}}"

checksum:
  name_template: "task_checksums.txt"

nfpms:
  - vendor: Task
    homepage: https://github.com/hedhyw/jlv
    maintainer: Maksym Kryvchun <hedhyw@yahoo.com>
    description: JSON Log Viewer tool.
    license: MIT
    formats:
      - deb
      - rpm
    file_name_template: "{{.ProjectName}}_{{.Os}}_{{.Arch}}"

brews:
  - name: jlv
    description: JSON Log Viewer tool.
    license: MIT
    homepage: https://github.com/hedhyw/homebrews
    repository:
      owner: hedhyw
      name: homebrew-main
    test: system "#{bin}/jlv", "-help"
    install: |-
      bin.install "jlv"
